# SPRING APPLICATION NAME
spring.application.name=MATERIAL-MS

# SERVER PORT
server.port=8081

# MYSQL DATABASE CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/MATERIAL
spring.datasource.username=root
spring.datasource.password=MysqlServer@3306

# JPA CONNECTION
spring.jpa.hibernate.ddl-auto=update
