# SPRING APPLICATION NAME
spring.application.name=EUREKA-SERVER

# SERVER PORT
server.port=8761

# EUREKA SERVER CONFIGURATION
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
