# SPRING APPLICATION NAME
spring.application.name=SHAPE-AVAILABILITY-MS

# SERVER PORT
server.port=8082

# MYSQL DATABASE CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/SHAPE_AVAILABILITY
spring.datasource.username=root
spring.datasource.password=MysqlServer@3306

# JPA CONNECTION
spring.jpa.hibernate.ddl-auto=update

